### PR TITLE
fixes issue #625

### PR DESCRIPTION
**Pull request by necenzurat**

### CODE REVIEW

**Comment by drbyte** [comment]
Since this PR is dependent on a newer version release of another package, shouldn't `composer.json` be updated as well?

ie: 
```diff
-        "spatie/db-dumper": "^2.7",
+        "spatie/db-dumper": "^2.9",
```

**Comment by necenzurat** [comment]
ye, @drbyte never saw that @freekmurze did a version bump

**Comment by drbyte** [comment]
The tests are failing due to errors finding/using `setGtidPurged`. Isn't that what this PR was to solve?

**Comment by freekmurze** [comment]
I'm thinking that option isn't so commonly used, so it doesn't deserve a separate key in the config file. Take a look at the docs on how to pass specific options to the db-dumper: https://docs.spatie.be/laravel-backup/v5/installation-and-setup#dumping-the-database

**Comment by necenzurat** [comment]
ah, cool, never saw that, you can ignore this pull request.

**Pull request closed without merging**
