### PR TITLE
Add translations for notifications

### PR DESCRIPTION
**Pull request by ptondereau**
This PR contains translations for notifications.

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Hmm if the translations happen via a "keys" system, shouldn't we use `trans` instead of `__`?

**Comment by ptondereau** [comment]
@sebastiandedeyne sure. I was not sure about it

**Comment by sebastiandedeyne** [comment]
Thanks! Not gonna merge yet, gonna let @freekmurze review first :)

**Comment by freekmurze** [comment]
Looks good to me! Thank you!

**Pull request merged**
