### PR TITLE
follow links

### PR DESCRIPTION
**Pull request by jorenvanhee**
FileSelection now follows symlinks. This is useful if you use a deployment tool like [Capistrano](http://capistranorb.com/documentation/getting-started/structure/).

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for your contribution. This is however a breaking change.

Let's make it non-breaking. Could you please introduce a config value `backup.source.files.followLinks` with a default value of `false`? Only if the config value is set to `true` the `followLinks` function may be called.

**Comment by jorenvanhee** [comment]
I did it like this now

```php
$finder = (new Finder())
    ->ignoreDotFiles(false)
    ->ignoreVCS(false)
    ->files()
    ->in($directory);

if (config('laravel-backup.backup.source.files.followLinks')) {
    $finder->followLinks();
}
```

Everything works, but the tests fail ("ReflectionException: Class config does not exist").
I honestly don't have a lot of experience with testing, and don't know how to fix it.

**Comment by freekmurze** [comment]
After reviewing this it don't like that `config` is called within the `FileSelection`-class. It this is better to add a `shouldFollowLinks`-method on the `FileSelection` class. 

You can read the config in [the `BackupJobFactory`-class](https://github.com/spatie/laravel-backup/blob/4969882d625dca8639514ff0c5aa610134412f25/src/Tasks/Backup/BackupJobFactory.php#L32) and call `shouldFollowLinks` there.

After you've done this modification the test 'll probably work again.

**Comment by jorenvanhee** [comment]
The tests do work again, thanks for the hint!
Is this try better?

**Comment by freekmurze** [comment]
Much better, thanks!

**Comment by freekmurze** [comment]
These changes are available in the newly tagged version `3.7.0`.
Thanks again for your contribution.

**Pull request merged**
