### PR TITLE
#340 - Filename is not set when zipping.

### PR DESCRIPTION
**Pull request by gtapps**
Solves the problem with a default filename not being set.

### CODE REVIEW

**Comment by freekmurze** [comment]
Great, could you also add a test to make sure that this does work?

**Comment by d0minationPT** [comment]
Hello, sure, will take care of this today.

**Comment by d0minationPT** [comment]
Done

**Comment by freekmurze** [comment]
According to Travis your tests seem to contain an error. Could you fix that?

**Comment by gtapps** [comment]
Seems like the issue with travis is because of files existing in the system?

**Comment by freekmurze** [comment]
Your change broke existing tests. Your change doesn't take into account that setting a filename is optional. I'll fix this quickly myself.

Thank you for your work on this.

**Comment by freekmurze** [comment]
Further investigation lead me to the root cause of the failing test. The default filename was set using php's `date` function which ignores the fixed datetime set by Carbon class in the tests.

**Comment by gtapps** [comment]
Awesome, thank you for the good extensions!

**Pull request merged**
