### PR TITLE
add translation to file sizes 

### PR DESCRIPTION
**Pull request by OthmanAlseagh**
@freekmurze

### CODE REVIEW

**Comment by freekmurze** [comment]
This PR makes the test fail, could you take a look at that?

**Comment by OthmanAlseagh** [comment]
I think you dont have translation as nova backup tool

**Comment by freekmurze** [comment]
Could you try if you could use this method to load the translations?
https://github.com/spatie/laravel-package-tools#working-with-translations

**Comment by OthmanAlseagh** [comment]
@freekmurze

**Comment by freekmurze** [comment]
The tests are failing, the need to pass in order for me to merge this in.

**Comment by freekmurze** [comment]
Closing as the tests are failing

**Pull request closed without merging**
