### PR TITLE
add BackupStarted event

### PR DESCRIPTION
**Pull request by ctf0**
u can use it like
```php
Event::listen('Spatie\Backup\Events\BackupStarted', function () {
    return logger(‘db backup has started’);
});
```

https://github.com/spatie/laravel-backup/issues/594

### CODE REVIEW

**Comment by introwit** [comment]
Hey thanks for the PR :) Could you please also add the tests too?

**Comment by ctf0** [comment]
sorry, i dont know how to write tests, however the pr isnt that big, its just an event that fires b4 the backup start

**Comment by freekmurze** [comment]
Let's make the event more useful by letting it hold a `BackupJob`. Also, fire off the event in the `run` function of `BackupJob`.

**Comment by ctf0** [comment]
@freekmurze am not sure what u r after, why we need the BackupJob ?

**Comment by freekmurze** [comment]
It would be nice of the consumer of the event to know which backup is starting.

**Comment by ctf0** [comment]
actually this was more intended for the client side alert, to inform the user that no writing ops is currently available, but okay, i can make it have the same footprint as BackupWasSuccessful , what u think ?

**Comment by freekmurze** [comment]
Let the event hold `BackupJob`

**Comment by ctf0** [comment]
apologize for the delay, but i found i can achieve what am after through https://laravel.com/docs/5.5/scheduling#task-hooks so no need for this event

**Pull request closed without merging**
