### PR TITLE
Add translations for backup destination properties

### PR DESCRIPTION
**Pull request by marcreichel**
This PR provides translations for the backup destination properties. Especially the keys.

### CODE REVIEW

**Comment by freekmurze** [comment]
I'm going to pass on this, as I don't want to maintain this. I think for notifications it makes sense to have translations as maybe non-developers might see them. I'm going to assume that people that execute the artisan command, can speak English.

**Comment by marcreichel** [comment]
@freekmurze But this PR was about the notifications. Not the artisan command 🤔 As I edited the `BaseNotification`.
So the emails (e.g.) are containing these (english) strings while the rest (subject and message) is translated (in german in my case). Or do I get something wrong?

image

**Comment by freekmurze** [comment]
Right! In that case, I'll have it!

Thanks for your work on this!

**Comment by marcreichel** [comment]
I'm happy I've changed your mind 😄
Thanks for merging 😊

**Pull request merged**
