### PR TITLE
Add list command

### PR DESCRIPTION
**Pull request by xeno010**
Add new list command: `php artisan backup:list`

> List all backups

unbenannt

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for your contribution. Awesome feature. I'll review it in detail in the coming days.

**Comment by freekmurze** [comment]
Some remarks on the output:
- the "create at" column should be renamed "Created at"
- it think it's better to output just one table for all backups. There should be a column named "Filesystem" that list the name of the filesystem the backup is saved on. 
- the "Expired in" column should be replace by and "Age" column that shows the age in days.

In your code you use several abbreviations like `$col` and `$v`. Please use full variable names, the are easier to read.

Could you make these changes? Then I'll pull.

**Comment by xeno010** [comment]
Thank you very much for your feedback.

I have done all the points.

Here a new screenshot
unbenannt2

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
This code of this PR is included in version `2.10.0`.

**Pull request merged**
